name: directus-cms-template
services:
  directus:
    image: directus/directus:latest
    ports:
      - ${DIRECTUS_PORT}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./migrations:/directus/migrations

    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}

      PUBLIC_URL: ${PUBLIC_URL}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}


      # Настройки для Refresh Token в Cookies
      REFRESH_TOKEN_COOKIE_NAME: "refresh_token"
      REFRESH_TOKEN_COOKIE_SECURE: "true"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      REFRESH_TOKEN_DOMAIN: "localhost"

      SESSION_COOKIE_SECURE: "false"
      SESSION_COOKIE_SAME_SITE: "lax"
      SESSION_COOKIE_DOMAIN: "localhost"

      EXTENSIONS_PATH: "/directus/extensions"
      EXTENSIONS_AUTO_RELOAD: "true"

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "'self' http://localhost:3000 http://localhost:5173"

      # EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      # EMAIL_FROM: ${EMAIL_FROM}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}